#!/usr/bin/env tsx
/**
 * EXAMPLE: Add Descript Video to Gallery
 *
 * Usage:
 *   npx tsx add-descript-video-example.ts
 *
 * Or edit the video details below and run
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://yvnuayzslukamizrlhwb.supabase.co';
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bnVheXpzbHVrYW1penJsaHdiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjI0NDg1MCwiZXhwIjoyMDcxODIwODUwfQ.natmxpGJM9oZNnCAeMKo_D3fvkBz9spwwzhw7vbkT0k';

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// ============================================================================
// EDIT THIS: Your Descript Video Details
// ============================================================================

const DESCRIPT_VIDEO = {
  title: 'Atnarpa Homestead Restoration - The Full Story',
  description: 'Watch the complete journey of restoring our family homestead with the help of A Curious Tractor and our community.',

  // Get this from Descript "Share" button
  video_url: 'https://share.descript.com/view/YOUR_VIDEO_ID_HERE',

  // Optional: Add custom thumbnail (Descript doesn't auto-generate)
  thumbnail_url: 'https://your-image-url.com/thumbnail.jpg', // or null

  tags: ['Atnarpa', 'Homestead', 'Restoration', 'Community', 'Partnership'],
  category: 'Community Story',
  service_area: 'Atnarpa Homestead On-Country Experiences',

  // Link to blog post if this video is featured in a blog
  source_blog_post_id: '79fb595d-5e9f-4f8e-ad6e-64a130eff8fb', // Your Atnarpa blog post
};

// ============================================================================
// NO NEED TO EDIT BELOW
// ============================================================================

async function addDescriptVideo() {
  console.log('📹 Adding Descript Video to Gallery\n');

  // Insert video - the database trigger will auto-extract video ID and generate embed code!
  const { data: video, error } = await supabase
    .from('videos')
    .insert({
      title: DESCRIPT_VIDEO.title,
      description: DESCRIPT_VIDEO.description,
      video_url: DESCRIPT_VIDEO.video_url,
      thumbnail_url: DESCRIPT_VIDEO.thumbnail_url,
      tags: DESCRIPT_VIDEO.tags,
      category: DESCRIPT_VIDEO.category,
      service_area: DESCRIPT_VIDEO.service_area,
      source_blog_post_id: DESCRIPT_VIDEO.source_blog_post_id,
      status: 'published',
      is_public: true,
      published_at: new Date().toISOString(),
      cultural_review: true,
      cultural_approved: true,
      elder_approved: true
    })
    .select()
    .single();

  if (error) {
    console.log('❌ Error adding video:', error.message);
    console.log('\nMake sure you:');
    console.log('  1. Ran add-descript-support.sql in Supabase');
    console.log('  2. Replaced YOUR_VIDEO_ID_HERE with actual Descript video ID');
    return;
  }

  console.log('✅ Descript video added successfully!\n');
  console.log('   ID:', video.id);
  console.log('   Title:', video.title);
  console.log('   Video Type:', video.video_type);
  console.log('   Video ID:', video.video_id);
  console.log('   Embed Code Generated:', video.embed_code ? 'Yes ✅' : 'No');

  console.log('\n📺 Auto-generated by database trigger:');
  console.log('   - Video ID extracted from URL');
  console.log('   - Embed code generated');
  console.log('   - Video type set to "descript"');

  console.log('\n🎬 View in gallery:');
  console.log('   http://localhost:3001/videos');

  console.log('\n📖 Linked to blog post:');
  console.log(`   http://localhost:3001/blog/${DESCRIPT_VIDEO.source_blog_post_id}`);

  console.log('\n💡 To add thumbnail:');
  console.log(`   UPDATE videos`);
  console.log(`   SET thumbnail_url = 'https://your-image-url.com/thumbnail.jpg'`);
  console.log(`   WHERE id = '${video.id}';`);
}

addDescriptVideo().catch(console.error);
